import {useStationsStore} from '@/store/stations'
import {useEffect} from 'react'
import {toast} from 'sonner'
import {open} from '@tauri-apps/plugin-dialog'
import {mkdir, writeTextFile} from '@tauri-apps/plugin-fs'
import {join} from '@tauri-apps/api/path'
import type {Station} from '@/types'

import {
	saveExportPath,
	fetch as fetchStations
} from '@/lib/stations'

import {
	Frown,
	FlaskConical,
	Pencil,
	X
} from 'lucide-react'

import {
	Select,
	SelectContent,
	SelectItem,
	SelectTrigger,
	SelectValue,
} from '@/components/ui/select'

import {
	AlertDialog,
	AlertDialogAction,
	AlertDialogCancel,
	AlertDialogContent,
	AlertDialogDescription,
	AlertDialogFooter,
	AlertDialogHeader,
	AlertDialogTitle,
	AlertDialogTrigger,
} from '@/components/ui/alert-dialog'

export default function Stations() {

	const stations = useStationsStore(state => state.list)
	const loading = useStationsStore(state => state.loading)
	const selectStation = useStationsStore(state => state.selectStation)
	const selectedStationId = useStationsStore(state => state.selectedStationId)

	const selectedStation = stations.find(s => s.id === selectedStationId)

	useEffect(() => {
		if (!stations.length)
			fetchStations()
	}, [])

	const onOpenFolder = async () => {

		if (!selectedStationId) return

		try {

			const selected = await open({directory: true})

			if (!selected)
				return

			const response = await saveExportPath({
				stationId: selectedStationId,
				exportPath: selected
			})

			if ('error' in response)
				throw new Error(response.error)

			toast.success('Automation path saved', {position: 'bottom-right'})

		} catch (err) {
			toast.error('Failed to save automation path', {
				description: err instanceof Error ? err.message : 'Unknown error',
				descriptionClassName: 'opacity-60 text-xs',
				position: 'bottom-right'
			})
		}

	}

	const onRemovePath = async () => {

		if (!selectedStationId) return

		try {

			const response = await saveExportPath({
				stationId: selectedStationId,
				exportPath: null
			})

			if ('error' in response)
				throw new Error(response.error)

			toast.success('Automation path removed', {position: 'bottom-right'})

		} catch (err) {
			toast.error('Failed to remove automation path', {
				description: err instanceof Error ? err.message : 'Unknown error',
				descriptionClassName: 'opacity-60 text-xs',
				position: 'bottom-right'
			})
		}

	}

	const onTestExport = async () => {
		const path = selectedStation?.exportPath
		if (!path) return

		try {
			const dir = await join(path, 'test')
			await mkdir(dir, {recursive: true})
			await writeTextFile(await join(dir, 'test.tpi'), 'TPI Test File\nGenerated by M1 CloudSync')
			await writeTextFile(await join(dir, 'test.dpl'), 'DPL Test File\nGenerated by M1 CloudSync')
			toast.success('Test files created', {position: 'bottom-right'})
		} catch (err) {
			toast.error('Failed to create test files', {
				description: err instanceof Error ? err.message : 'Unknown error',
				descriptionClassName: 'opacity-60 text-xs',
				position: 'bottom-right'
			})
		}
	}

	if (loading)
		return (
			<div className="p-4 bg-gray-100 grow">
				<div className="p-3 space-y-4">
					<div className="w-[35%] h-3 bg-gray-200 rounded-full animate-pulse delay-0" />
					<div className="w-[25%] h-3 bg-gray-200 rounded-full animate-pulse delay-100" />
					<div className="w-[40%] h-3 bg-gray-200 rounded-full animate-pulse delay-200" />
				</div>
			</div>
		)

	if (!stations.length)
		return (
			<div className="p-4 bg-gray-100 grow flex items-center justify-center">
				<div className="text-center w-1/2">
					<Frown className="size-30 mx-auto mb-6 text-gray-300" />
					<div className="text-gray-500">
						No stations found in your account,
						<br/>
						click <button className="px-1.5 py-0.5 rounded-md bg-gray-200 text-gray-600 cursor-pointer hover:bg-gray-300/70 transition-all" onClick={fetchStations}>here</button> to try again.
					</div>
				</div>
			</div>
		)

	return (
		<div className="p-4 bg-gray-100 grow space-y-4">

			<div className="flex items-center gap-x-3">

				<Select value={selectedStationId?.toString()} onValueChange={(value) => selectStation(parseInt(value))}>
					<SelectTrigger className="w-[180px] cursor-pointer bg-white">
						<SelectValue placeholder="Select station" />
					</SelectTrigger>
					<SelectContent>
						{stations.map((item: Station) => (
							<SelectItem key={item.id} value={item.id.toString()}>{item.name}</SelectItem>
						))}
					</SelectContent>
				</Select>

			</div>

			<div className="p-4 bg-white ring-1 ring-slate-200 shadow-sm sm:rounded-lg max-w-full">

				{selectedStation?.exportPath
					? <div className="group flex items-center gap-x-2">
						<div className="text-sm text-slate-600 grow">{selectedStation.exportPath}</div>
						<button onClick={onTestExport} className="p-1.5 rounded-md text-slate-400 hover:text-amber-600 hover:bg-amber-50 cursor-pointer transition-colors opacity-0 group-hover:opacity-100">
							<FlaskConical className="size-3.5" />
						</button>
						<button onClick={onOpenFolder} className="p-1.5 rounded-md text-slate-400 hover:text-slate-600 hover:bg-slate-100 cursor-pointer transition-colors">
							<Pencil className="size-3.5" />
						</button>
						<AlertDialog>
							<AlertDialogTrigger asChild>
								<button className="p-1.5 rounded-md text-slate-400 hover:text-red-500 hover:bg-red-50 cursor-pointer transition-colors">
									<X className="size-3.5" />
								</button>
							</AlertDialogTrigger>
							<AlertDialogContent>
								<AlertDialogHeader>
									<AlertDialogTitle>Remove automation path</AlertDialogTitle>
									<AlertDialogDescription>
										Are you sure you want to remove the automation export path for this station?
									</AlertDialogDescription>
								</AlertDialogHeader>
								<AlertDialogFooter>
									<AlertDialogCancel>Cancel</AlertDialogCancel>
									<AlertDialogAction onClick={onRemovePath}>Remove</AlertDialogAction>
								</AlertDialogFooter>
							</AlertDialogContent>
						</AlertDialog>
					</div>
					: <div className="text-center text-gray-500 cursor-pointer" onClick={onOpenFolder}>
						No automation path set for this station, click <span className="p-1 rounded-md bg-gray-200 hover:bg-gray-300 transition-colors">here</span> to select a folder.
					</div>
				}

			</div>

		</div>
	)
}
